### ISSUE TITLE
LineChart: logarithmic plot

### ISSUE THREAD

**Issue by malmr** [imaNNeo/fl_chart#1394] opened 2023-07-17 12:58 UTC
Dear community,

are there any plans to implement a logarithmic x / y axis?
Or is there a workaround to plot and label the values different, in such way that my log values will be plotted equidistant?

Thanks, that would be very helpful.

**Comment by pritsawa** [comment] 2023-08-17 02:29
https://www.youtube.com/watch?v=Wa0L9iYkSjc

**Comment by obiwan007** [comment] 2023-09-08 15:24
Probably you just need to log your y values before plotting... And somehow do some 1 10 100 1000 on the y-axis...

**Comment by imaNNeo** [comment] 2023-10-01 09:16
Duplicate of #434

**Closed by imaNNeo** 2023-10-01 09:16 UTC
