### ISSUE TITLE
[Question] - Horizontal BarChart

### ISSUE THREAD

**Issue by brenoasm** [imaNNeo/fl_chart#1099] opened 2022-07-19 14:10 UTC
Is there a way to render barCharts horizontally? I tried to search in the docs and do something in the code, but I wasn't very successful. If yes, would be a nice improve to put it into the docs. Thanks.

**Comment by ZingerLittleBee** [comment] 2022-09-05 08:54
Hi,
Do you got it, I'am confused too.
I'am tried to use `Transform.rotate`, but seem not good.

**Comment by leandrorazevedo** [comment] 2022-09-27 11:52
I have the same issue. I've searched through all the documentation and haven't found anything.

**Comment by Mae623** [comment] 2022-12-15 10:08
The same with me

**Comment by Mae623** [comment] 2022-12-15 10:10
let's have a look on #113

**Comment by imaNNeo** [comment] 2023-01-30 12:00
Yes it is duplicate of #113.

**Closed as completed** 2023-04-10 16:08 UTC
Labels: duplicate
