### ISSUE TITLE
PieChart not fully draw in ios devices when have only one section

### ISSUE THREAD

**Issue by islavstan** [imaNNeo/fl_chart#1515] opened 2023-11-30 13:02 UTC
PieChart not fully draw in ios devices when have only one section

<img width="310" alt="Снимок экрана 2023-11-30 в 15 01 35" src="https://github.com/imaNNeo/fl_chart/assets/13497056/5d5835b0-fd16-4e31-9de7-db1950ef675e">

border doesn't help too
<img width="331" alt="Снимок экрана 2023-11-30 в 15 02 20" src="https://github.com/imaNNeo/fl_chart/assets/13497056/0a7aabbf-3ce0-48a2-9199-011259de5894">

**Comment by imaNNeo** [comment] 2023-12-03 23:09
I couldn't reproduce it.
Can you please share a reproducible code? (a main.dart file content)
![Simulator Screenshot - iPhone 15 Pro Max - 2023-12-04 at 00 09 19](https://github.com/imaNNeo/fl_chart/assets/7009300/2a8c26a9-e928-47ed-bc1e-1a9acd87c4e0)

**Comment by islavstan** [comment] 2023-12-04 12:26
![Simulator Screenshot - iPhone 14 - 2023-12-04 at 14 26 12](https://github.com/imaNNeo/fl_chart/assets/13497056/20ef519f-7d78-47bc-a33b-e8c82d09fb60)

**Comment by islavstan** [comment] 2023-12-04 12:27
I think problem in PieChartPainter
if (sectionDegree == 360) {
        _sectionPaint
          ..color = section.color
          ..strokeWidth = section.radius
          ..style = PaintingStyle.stroke;
        canvasWrapper.drawCircle(
          center,
          centerRadius + section.radius / 2,
          _sectionPaint,
        );

**Comment by imaNNeo** [comment] 2023-12-15 21:12
Got it!

**Comment by imaNNeo** [comment] 2023-12-15 21:27
Merged into master

**Comment by imaNNeo** [comment] 2023-12-25 14:59
Landed in [0.66.0](https://github.com/imaNNeo/fl_chart/releases/tag/0.66.0)

**Closed by imaNNeo** 2023-12-25 14:59 UTC
Labels: bug, Pie Chart
