### ISSUE TITLE
Need BiaxialLineChart in flutter like Recharts

### ISSUE THREAD

**Issue by vigneshsskv** [imaNNeo/fl_chart#851] opened 2021-12-11 11:59 UTC
**Is your feature request relasted to a problem? Please describe.**
Need a feature like biaxial line chart in flutter which is already available in react js

**Describe the solution you'd like**
https://recharts.org/en-US/examples/BiaxialLineChart

**Describe alternatives you've considered**
https://pub.dev/packages/fcharts

**Comment by imaNNeo** [comment] 2023-01-30 13:31
Duplicate of #429

**Closed by imaNNeo** 2023-01-30 13:31 UTC
