### ISSUE TITLE
Support horizontal Bar chart

### ISSUE THREAD

**Issue by Flynn2018** [imaNNeo/fl_chart#1363] opened 2023-06-13 10:21 UTC
It seems that this plugin doesn't support horizontal Bar chart. That is to say, the columns are presented horizontally. This is a relatively common application scenario.

**Comment by Mrprey** [comment] 2023-06-14 20:46
this is a feature i really missed and ended up rotating the widget itself to get this functionality

**Comment by imaNNeo** [comment] 2023-06-14 21:40
Duplicate of #113

**Closed by imaNNeo** 2023-06-14 21:40 UTC
