### ISSUE TITLE
 Unsupported operation: Platform._environment

### ISSUE THREAD

**Issue by pratikNavapara009** [imaNNeo/fl_chart#1566] opened 2024-01-24 11:07 UTC
** Don't make a duplicate issue.
You can search in issues to make sure there isn't any already opened issue with your concern.

**Describe the bug**

**To Reproduce**
Provide us a completely reproducible code (contains the main function) in a `main.dart` file, it helps us to find the bug immediately.

**Screenshots**
If applicable, add screenshots, or videoshots to help explain your problem.

**Versions**
 - which version of the Flutter are you using?
 - which version of the FlChart are you using?

**Comment by imaNNeo** [comment] 2024-02-06 21:35
Please provide more information and don't send the default template as the issue description.

**Comment by NotTsunami** [comment] 2024-02-08 18:42
Duplicate of #1565

**Closed** 2024-02-10 11:51 UTC
Labels: Lack of Information
