### ISSUE TITLE
fl_chart can support This effect? 

### ISSUE THREAD

**Issue by helloworkcupid** [imaNNeo/fl_chart#1308] opened 2023-04-13 05:07 UTC
** Don't make a duplicate issue.
You can search in issues to make sure there isn't any already opened issue with your concern.

**Is your feature request relasted to a problem? Please describe.**

**Describe the solution you'd like**

This effect, use lineChart
I want to achieve the effect shown here, with the Y-axis adaptive and each scale corresponding to a line, and the X-axis as before.
pleaset ,thank you 
<img width="782" alt="image" src="https://user-images.githubusercontent.com/25734405/231658610-21b2d5eb-d917-4894-8b2f-5b163f85fc32.png">

**Describe alternatives you've considered**

**Additional context**

**Comment by helloworkcupid** [comment] 2023-04-13 05:07
please tell me the main code , thank you

**Comment by helloworkcupid** [comment] 2023-04-14 01:44
set logarithmic scale ,in fl_chart ,how can i do it ?

**Comment by imaNNeo** [comment] 2023-04-14 22:51
Duplicate of #434

**Closed by imaNNeo** 2023-04-14 22:51 UTC
Labels: duplicate, Line Chart
