### ISSUE TITLE
Thorny LineChart

### ISSUE THREAD

**Issue by normidar** [imaNNeo/fl_chart#1625] opened 2024-04-01 08:04 UTC
**Don't make a duplicate issue.**
Okey

**Describe the bug**
Line LineChart is thorny.

**To Reproduce**
To show sensors data on Line Chart.(33 fps & show 100 data in LineChart)

**Screenshots**

https://github.com/imaNNeo/fl_chart/assets/36730656/13b1d7cc-e922-4b53-90bd-913938fa8ee5

**Versions**
 - which version of the Flutter are you using?
   - 3.19.4
 - which version of the FlChart are you using?
   - fl_chart: 0.67.0

**Comment by eloayoubi** [comment] 2024-04-03 07:36
![grafik](https://github.com/imaNNeo/fl_chart/assets/127199004/e168e254-51b6-4fa1-b9b7-1d22928f4fe9)
We got the same Issue since the Flutter 3.19.4 Update - fl_chart: 0.67.0

**Comment by ManuelRauber** [comment] 2024-04-11 12:53
I can confirm this behavior as well. Same version as @eloayoubi running on an iOS device.

**Comment by e4ky** [comment] 2024-04-16 00:39
try this: #1618 to disable linechart's default animation.

**Comment by eloayoubi** [comment] 2024-04-16 06:46
> try this: #1618 to disable linechart's default animation.

I have tried the suggestion to disable the animation for the Linechart with Duration.zero

It did not fix this issue.

**Comment by luisbelo91** [comment] 2024-05-10 13:47
same issue since the Flutter 3.19.x update - fl_chart: 0.55.2 - only reproducible on iOS

**Comment by hngouveia01** [comment] 2024-05-17 10:10
It seems to be related with Impeller renderer at Flutter version 3.19.x
Looks like it is fixed in Flutter version 3.22
As a workaround you could try to disable the Impeller engine by following this documentation:

https://docs.flutter.dev/perf/impeller#:~:text=Flutter%20enables%20Impeller%20by%20default,to%20the%20flutter%20run%20command.&text=To%20disable%20Impeller%20on%20iOS%20when%20deploying%20your%20app%2C%20add,your%20app%27s%20Info.plist%20file.

If it is not fixed, then it is not the Impeller.

This is the issue on Flutter repository:
https://github.com/flutter/flutter/issues/146975

Although is about gradient being dithered, it applies to those awkward lines. My own experience ;)

**Comment by hngouveia01** [comment] 2024-05-17 10:12
Also, if after upgrading Flutter to 3.22 and the issue persists... Feel free to open an issue on the Flutter repo.  :)

**Comment by techouse** [comment] 2024-05-23 17:22
I still see this on Flutter 3.22.1 using Impeller. It's fine running on Skia.

**Comment by techouse** [comment] 2024-05-23 17:43
@normidar @eloayoubi @luisbelo91 @ManuelRauber @hngouveia01 should we / you  / me make a bug report on flutter/flutter?

**Comment by hngouveia01** [comment] 2024-05-24 16:17
> @normidar @eloayoubi @luisbelo91 @ManuelRauber @hngouveia01 should we / you / I make a bug report on flutter/flutter?

Hi, @techouse. Don't get me wrong, I know you're a tech savvy :)
But there are two ways of disabling the Impeller. Have you tried both? Via .plist and command line?
I'm asking this because I found this comment here, and he got different results by disabling via .plist
https://github.com/imaNNeo/fl_chart/issues/1410#issuecomment-1664294771

I'll get more info about this and report a bug about the Impeller. Thanks!

**Comment by hngouveia01** [comment] 2024-05-24 16:34
@techouse, check this new PR merged in 3.23 and was present on 3.22 version:
https://github.com/flutter/flutter/issues/146648

General fixes being merged:
https://github.com/flutter/engine/commits/main/impeller

**Comment by hngouveia01** [comment] 2024-05-24 16:36
And it seems we have these two workarounds:

[jonahwilliams](https://github.com/jonahwilliams)
The reason this is happening is a bug with Path.close(). We should be ignoring the final close call which is supposed to draw a line to the path start - since this is stroke and not a fill.

So we should fix this, but in this case you don't need/shouldn't use the Path.close at the end there. Because the fix is going to be ignoring it anyway

**Comment by techouse** [comment] 2024-05-24 16:44
> Hi, @techouse. Don't get me wrong, I know you're a tech savvy :) But there are two ways of disabling the Impeller. Have you tried both? Via .plist and command line? I'm asking this because I found this comment here, and he got different results by disabling via .plist [#1410 (comment)](https://github.com/imaNNeo/fl_chart/issues/1410#issuecomment-1664294771)

I got it disabled via the Property list.

```xml
<key>FLTEnableImpeller</key>
<false/>
```

**Comment by techouse** [comment] 2024-05-25 09:01
@hngouveia01 hmm, I tried just naively removing `.close()` in these places

- https://github.com/imaNNeo/fl_chart/blob/2ecde9a40da3206af0c27dc783c1a538947d5aa6/lib/src/chart/pie_chart/pie_chart_painter.dart#L217
- https://github.com/imaNNeo/fl_chart/blob/2ecde9a40da3206af0c27dc783c1a538947d5aa6/lib/src/chart/radar_chart/radar_chart_painter.dart#L374
- https://github.com/imaNNeo/fl_chart/blob/2ecde9a40da3206af0c27dc783c1a538947d5aa6/lib/src/chart/line_chart/line_chart_painter.dart#L643
- https://github.com/imaNNeo/fl_chart/blob/2ecde9a40da3206af0c27dc783c1a538947d5aa6/lib/src/chart/line_chart/line_chart_painter.dart#L687

however the line is still jagged using Impeller.

**Comment by techouse** [comment] 2024-05-25 10:18
I found a few related issues:
- https://github.com/flutter/flutter/issues/147139
- https://github.com/flutter/flutter/issues/148323
And a PR that apparently fixes them https://github.com/flutter/engine/pull/52978

**Comment by techouse** [comment] 2024-06-13 12:23
Still problematic with Flutter v3.22.2

**Comment by techouse** [comment] 2024-07-18 11:04
Still problematic with Impeller in Flutter v3.22.3

**Comment by techouse** [comment] 2024-07-19 13:10
@imaNNeo, since you have the greatest level of detailed insight here, maybe you could open a ticket in flutter/flutter?

P.S. Pie charts are also broken.

**Comment by imaNNeo** [comment] 2024-07-19 19:31
> @imaNNeo, since you have the greatest level of detailed insight here, maybe you could open a ticket in flutter/flutter?

There's no special insight needed here, so you can just have a simple path with some lineTo, and path.close() call to reproduce it. But before that, we need to check to see if there is already an opened issue which is exactly related to this one. Otherwise, it would be nice if you open an issue. Because it needs some time to write the details and provide the reproducible code. So at the moment, I found a little time and I prefer to consume it for the fl_chart issues.

So I appreciate if you follow it up and open an issue if it doesn't exist already.

Cheers!

**Comment by techouse** [comment] 2024-08-23 12:18
Looks like this has been fixed in Flutter v3.24.1 🚀

**Comment by imaNNeo** [comment] 2024-08-26 22:04
> Looks like this has been fixed in Flutter v3.24.1 🚀

Nice! Can others please validate the fix with their use cases?
Then we can close this issue.
Btw, I'm really happy with the power of open-source. I didn't contribute much here, but you (the contributors) talked together, proposed some solutions, and found the related issues in the flutter, ...
You are amazing! 
Thanks for contributing!

**Comment by normidar** [comment] 2024-08-27 06:40
I found the app from that time and verified it again. Indeed, it was fixed.

https://github.com/user-attachments/assets/18fa047b-0dd7-45ba-95c4-4890f7bc912b

**Versions**
 - which version of the Flutter are you using?
   - 3.24.0
 - which version of the FlChart are you using?
   - fl_chart: 0.69.0

**Comment by techouse** [comment] 2024-08-27 09:32
> Then we can close this issue.
Indeed. 😎

**Closed** 2024-11-20 16:33 UTC
Labels: bug, Fundamental, Flutter Engine Related
