### ISSUE TITLE
Support an additional Y axis on the right of the line chart

### ISSUE THREAD

**Issue by bigbang489** [imaNNeo/fl_chart#1417] opened 2023-08-14 14:01 UTC
Assume that we have 2 line charts. The left axis showcases S&P 500 index, while the right axis features the second line, representing the P/E ratio, see the below image:
![image](https://github.com/imaNNeo/fl_chart/assets/29498440/d5482139-9c58-4479-bcf5-2998ba986ac0)

**Comment by pritsawa** [comment] 2023-08-17 02:29
https://www.youtube.com/watch?v=Wa0L9iYkSjc

**Comment by obiwan007** [comment] 2023-09-08 15:18
Would be really nice to have multi-y axis support for line charts.

**Comment by mivoligo** [comment] 2023-11-09 10:07
Looks like a duplicate of #429

**Comment by imaNNeo** [comment] 2023-11-11 01:46
@mivoligo YOu're right. Thanks!
Please follow the #429 issue

**Closed by imaNNeo** 2023-11-11 01:46 UTC
