### ISSUE TITLE
How to set rightTitles diffrent range axisY2?

### ISSUE THREAD

**Issue by Mecil9** [imaNNeo/fl_chart#493] opened 2020-11-09 08:08 UTC
![image](https://user-images.githubusercontent.com/2948534/98515102-80283900-22a5-11eb-9c94-41b098a42994.png)

rightTitle y-range as same as left.
i wanna change the rightitles range from +500~-500.leftTitles range +90--90.how can i do?

**Comment by imaNNeo** [comment] 2023-01-30 17:30
Duplicate of #429

**Closed** 2023-01-30 17:31 UTC
Labels: duplicate, Line Chart
