### ISSUE TITLE
Disable tip inside chart when i touch

### ISSUE THREAD

**Issue by helloo0-0oworld** [imaNNeo/fl_chart#791] opened 2021-10-13 14:16 UTC
Please tell me how to disable tip (text: 4.0) when i touch inside chart. I don't want to show it when i touch or long press. Pls help me
<img width="88" alt="Screen Shot 2021-10-13 at 21 16 20" src="https://user-images.githubusercontent.com/32776884/137151080-c2b5ddc4-856a-4e75-80fd-af07ecf1d086.png">

**Comment by pshivvy** [comment] 2021-10-13 16:33
Duplicate of #33.

You can return `null` in `getTooltipItems` in order to disable the text.

`lineTouchData: LineTouchData(
            touchTooltipData: LineTouchTooltipData(
                getTooltipItems: (touchedBarSpots) {
                  return touchedBarSpots.map((barSpot) {
                    return null;
                  }).toList();
                }),
          )`

**Comment by imaNNeoFighT** [comment] 2021-10-14 22:32
You're right. Thanks @pshivvy!

**Closed as completed by imaNNeoFighT** 2021-10-14 22:32 UTC
Labels: duplicate, Line Chart
